@startuml creating-templates
title Creating Templates


start
:Create a new template, with a name;

if ($EDITOR environment variable is set?) then (yes)

    if (Template directory exists?) then (yes)
    else (no)

        :Create template directory;
        if (Error?) then (yes)
            :Report error to user;
            stop
        else (no)

        endif
        
    endif

    if (Template exists?) then (yes)
        :Prompt user if they want to overwrite;

        if (Overwrite?) then (yes)
        else (no)
            stop
        endif

    else (no)
    endif

    :Generate scaffold template for user;
    :Open template in $EDITOR;


else (no)
    :Instruct user to set $EDITOR to
    their preferred text editor;
endif

stop

@enduml