@startuml file-generation
title File(s) Generation

start

:Generate template with
user-specified options;

if (Template exists in\ntemplate directory?) then (yes)

    :Unmarshal template file;

    while (More templates and no errors?) is (true)
        :Create parent directories if needed;

        :Apply options and defaults
        to template contents;

        :Write templatized contents to file;
    endwhile (false)

    if (Error occurred?) then (yes)
        :Report issue to user;
    else (no) 
        :Report success to user;
    endif


else (no)
    :Report error to user;
endif

stop

@enduml