@startuml listing-templates
title Listing Templates

start

:List all templates;

if (Template directory exists?) then (yes)

    if (Template directory is empty?) then (yes)
        :Report that directory is empty;

    else (no)

        while (More templates?) is (yes)

            :Unmarshal template;
            :Get any default options;
            :Display metrics: name of template, 
            how many files, default options, etc.;

        endwhile (no)

    endif

else (no)

    :Create template directory;
    :Report template directory creation
    success or failure;

endif

stop

@enduml