@startuml use-case
left to right direction

actor User as user

rectangle tmpl {
    user --> (Generate a file, with options)
    user --> (Generate a project, with options)
    user --> (Create new templates,\nwith options and defaults)
    user --> (Edit existing templates)
    user --> (List existing templates,\nwith any options and defaults)
}


@enduml